"""
HQ Command GUI Styling System.

Centralizes design tokens, theme configuration, and component styles
for the HQ Command GUI application.
"""

from .theme import (
    # Color tokens
    PRIMARY,
    PRIMARY_LIGHT,
    PRIMARY_CONTRAST,
    SECONDARY,
    ACCENT,
    SUCCESS,
    DANGER,
    WARNING,
    NEUTRAL_900,
    NEUTRAL_700,
    NEUTRAL_500,
    NEUTRAL_200,
    NEUTRAL_100,
    SURFACE_LIGHT,
    SURFACE_DARK,
    BACKGROUND_PRIMARY,
    BACKGROUND_SECONDARY,
    SURFACE_ELEVATED,
    BORDER_COLOR,
    BORDER_COLOR_STRONG,
    DIVIDER_COLOR,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    TEXT_TERTIARY,
    # Typography
    FONT_FAMILY,
    FONT_SIZE_H1,
    FONT_SIZE_H2,
    FONT_SIZE_H3,
    FONT_SIZE_H4,
    FONT_SIZE_H5,
    FONT_SIZE_H6,
    FONT_SIZE_BODY,
    FONT_SIZE_SMALL,
    FONT_SIZE_TINY,
    # Spacing
    SPACING_BASE,
    SPACING_XS,
    SPACING_SM,
    SPACING_MD,
    SPACING_LG,
    SPACING_XL,
    MIN_TOUCH_TARGET,
    # Component dimensions
    NAV_RAIL_WIDTH,
    STATUS_BAR_HEIGHT,
    CONTEXT_DRAWER_WIDTH,
    # Animation
    TRANSITION_FAST,
    TRANSITION_NORMAL,
    TRANSITION_SLOW,
    EASING_STANDARD,
    EASING_DECELERATE,
    EASING_ACCELERATE,
    # Theme builders
    build_palette,
    component_styles,
    focus_ring_stylesheet,
    Theme,
    ThemeVariant,
    DEFAULT_THEME,
)

__all__ = [
    # Color tokens
    "PRIMARY",
    "PRIMARY_LIGHT",
    "PRIMARY_CONTRAST",
    "SECONDARY",
    "ACCENT",
    "SUCCESS",
    "DANGER",
    "WARNING",
    "NEUTRAL_900",
    "NEUTRAL_700",
    "NEUTRAL_500",
    "NEUTRAL_200",
    "NEUTRAL_100",
    "SURFACE_LIGHT",
    "SURFACE_DARK",
    "BACKGROUND_PRIMARY",
    "BACKGROUND_SECONDARY",
    "SURFACE_ELEVATED",
    "BORDER_COLOR",
    "BORDER_COLOR_STRONG",
    "DIVIDER_COLOR",
    "TEXT_PRIMARY",
    "TEXT_SECONDARY",
    "TEXT_TERTIARY",
    # Typography
    "FONT_FAMILY",
    "FONT_SIZE_H1",
    "FONT_SIZE_H2",
    "FONT_SIZE_H3",
    "FONT_SIZE_H4",
    "FONT_SIZE_H5",
    "FONT_SIZE_H6",
    "FONT_SIZE_BODY",
    "FONT_SIZE_SMALL",
    "FONT_SIZE_TINY",
    # Spacing
    "SPACING_BASE",
    "SPACING_XS",
    "SPACING_SM",
    "SPACING_MD",
    "SPACING_LG",
    "SPACING_XL",
    "MIN_TOUCH_TARGET",
    # Component dimensions
    "NAV_RAIL_WIDTH",
    "STATUS_BAR_HEIGHT",
    "CONTEXT_DRAWER_WIDTH",
    # Animation
    "TRANSITION_FAST",
    "TRANSITION_NORMAL",
    "TRANSITION_SLOW",
    "EASING_STANDARD",
    "EASING_DECELERATE",
    "EASING_ACCELERATE",
    # Theme builders
    "build_palette",
    "component_styles",
    "focus_ring_stylesheet",
    "Theme",
    "ThemeVariant",
    "DEFAULT_THEME",
]
